class AppError extends Error {
  constructor(message, statusCode) {
    super(message);

    this.statusCode = statusCode;
    this.status = `${statusCode}`.startsWith('4') ? 'fail' : 'error'; // if status code starts with 4, it's a fail, otherwise it's an error
    this.isOperational = true; // operational errors are errors that are generated by the application
    Error.captureStackTrace(this, this.constructor); // captures the stack trace
  }
}

module.exports = AppError;
